### ISSUE TITLE
InOutNonic

### ISSUE THREAD

**Issue by vanilla-plus** [Michaelangel007/easing_optimizations#1]
Before I go on, I have to say this is the best easing guide I've ever seen! I've learned a lot by going through this even briefly.

I wanted to raise that the InOutNonic example in the documentation is currently:
`function InOutNonic     (p) { var m=p-1,t=p*2; if (t < 1) return p*t*t*t*t*t*t*t*t; return 1-m*m*m*m*m*m*m*m*m*256; },`

But I think, based on the pattern of other InOuts, it should be:
`function InOutNonic     (p) { var m=p-1,t=p*2; if (t < 1) return p*t*t*t*t*t*t*t*t; return 1+m*m*m*m*m*m*m*m*m*256; },`

Is that correct?

**Comment by Michaelangel007** [comment]
Sorry for the delay.  Glad you found the guide useful.

Thanks for the catch! Fixed and attributed to you.
